global_plotting_options:
 regions: ["global"]
 image_format : "png" 
 animation_format: "mp4"
 dpi_val : 300
 fps: 2
 GLORYS:
  use_datashader: false

evaluation:
  metrics  : ["rmse", "froct"]
  regions: ["global"]
  summary_plots : true
  ratio_plots : false
  heat_maps : false
  summary_dir: "./plots/"
  plot_ensemble: "false" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: false

default_streams:
  GLORYS:
    channels: ["zos", "thetao_0.494025m", "so_0.494025m", "uo_0.494025m", "vo_0.494025m", "thetao_109.729m", "so_109.729m", "uo_109.729m", "vo_109.729m", "thetao_541.089m", "so_541.089m", "uo_541.089m", "vo_541.089m"]
    evaluation:
      forecast_step: "all"
      sample: "all"
    plotting:
      forecast_step: "all"
      sample: "all"
      plot_maps: true
      plot_bias: true
      plot_target: true
      plot_histograms: true
      plot_animations: true