streams_directory: "./config/streams/fesom/"

# ae_local_num_queries: 2
# ae_adapter_embed: 128
# ae_local_dim_embed: 1024
# ae_local_num_blocks: 4
# ae_local_num_heads: 16

start_date:  '2000-01-01 00:00:00'
end_date: '2009-12-31 00:00:00'
start_date_val: '2000-01-01 00:00:00'
end_date_val: '2000-12-31 00:00:00'

num_epochs: 111
samples_per_epoch: 32 #16392
samples_per_validation: 16 #1024
shuffle: True

loader_num_workers: 2
training_mode: "forecast"

lr_max: 2e-5
