FESOM_NODE_SALT:
  type: fesom
  stream_id: 2141
  filenames:
  - ocean_node
  loss_weight: 1.0
  source:
  - salt_2
  - salt_7
  - salt_15
  - salt_25
  - salt_45
  - salt_95
  - sss
  target:
  - salt_2
  - salt_7
  - salt_15
  - salt_25
  - salt_45
  - salt_95
  - sss
  location_weight: cosine_latitude
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 128
  tokenize_spacetime : True
  max_num_targets: -1 
  embed : 
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    num_layers : 2
    num_heads : 4
    # sampling_rate : 0.2
  pred_head :
    ens_size : 1
    num_layers : 1
